# This YAML file is created to build web app and run test cases
name: Webapp Test

on:
  pull_request:
    branches:
      - main
    
jobs:
  build_webapp_and_run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo systemctl start mysql.service

      - name: Configure MySQL
        run: |
          # Set root password
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '${{ secrets.ROOT_PASSWORD }}';"
          sudo mysql -u root -p${{ env.MYSQL_ROOT_PASSWORD }} -e "CREATE DATABASE \`${{ secrets.DB_NAME }}\`;"
          sudo mysql -u root -p${{ env.MYSQL_ROOT_PASSWORD }} -e "CREATE USER '${{ secrets.DB_USERNAME }}'@'localhost' IDENTIFIED BY '${{ secrets.DB_PASSWORD }}';"
          sudo mysql -u root -p${{ env.MYSQL_ROOT_PASSWORD }} -e "GRANT ALL PRIVILEGES ON \`${{ secrets.DB_NAME }}\`.* TO '${{ secrets.DB_USERNAME }}'@'localhost';"
          sudo mysql -u root -p${{ env.MYSQL_ROOT_PASSWORD }} -e "FLUSH PRIVILEGES;"

      - name: Configure environment variables
        run: |
          echo > .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo DB_NAME=${{ secrets.DB_NAME }} >> .env
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env
          echo DB_DIALECT=${{ secrets.DB_DIALECT }} >> .env

      - name: Install Node dependencies
        run: npm install

      - name: Run tests
        run: npm test
